
CREATE DATABASE [SrToDo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SrToDo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SrToDo.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SrToDo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SrToDo_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SrToDo] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [SrToDo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SrToDo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SrToDo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SrToDo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SrToDo] SET ARITHABORT OFF 
GO
ALTER DATABASE [SrToDo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SrToDo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SrToDo] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SrToDo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SrToDo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SrToDo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SrToDo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SrToDo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SrToDo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SrToDo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SrToDo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SrToDo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SrToDo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SrToDo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SrToDo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SrToDo] SET  READ_WRITE 
GO
ALTER DATABASE [SrToDo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SrToDo] SET  MULTI_USER 
GO
ALTER DATABASE [SrToDo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SrToDo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SrToDo] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SrToDo]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SrToDo]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SrToDo] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


USE [SrToDo]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ToDo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](50) NOT NULL,
	[Description] [ntext] NULL,
	[Priority] [int] NULL,
	[Done] [bit] NULL,
	[Created] [datetime2](7) NULL,
	[Updated] [datetime2](7) NULL,
 CONSTRAINT [PK_ToDo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_ToDo_Name] ON [dbo].[ToDo]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
